-- Daily shortage and stagnant-inventory facts produced by the Hermes scheduled job.
CREATE TABLE IF NOT EXISTS llx_ai_dashboard_inventory_risk_daily (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL DEFAULT 1,
  snapshot_date date NOT NULL,
  risk_type varchar(16) NOT NULL,
  risk_level varchar(16) NOT NULL DEFAULT 'medium',
  product_id integer NOT NULL DEFAULT 0,
  product_ref varchar(128) NOT NULL,
  product_label varchar(255) DEFAULT NULL,
  warehouse_id integer DEFAULT NULL,
  warehouse_ref varchar(64) DEFAULT NULL,
  current_stock decimal(24,8) DEFAULT NULL,
  daily_consumption decimal(24,8) DEFAULT NULL,
  days_to_stockout decimal(10,2) DEFAULT NULL,
  forecast_stockout_date date DEFAULT NULL,
  desired_stock decimal(24,8) DEFAULT NULL,
  alert_stock decimal(24,8) DEFAULT NULL,
  impact_amount decimal(24,8) DEFAULT NULL,
  affected_order_count integer NOT NULL DEFAULT 0,
  affected_order_refs text,
  last_movement_date date DEFAULT NULL,
  risk_reason text,
  source_run_id integer DEFAULT NULL,
  created_at datetime NOT NULL,
  tms timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ai_inventory_risk_daily (entity, snapshot_date, risk_type, product_id, warehouse_id),
  KEY idx_ai_inventory_risk_daily_date (entity, snapshot_date),
  KEY idx_ai_inventory_risk_daily_type (entity, snapshot_date, risk_type),
  KEY idx_ai_inventory_risk_daily_level (entity, snapshot_date, risk_level)
) ENGINE=innodb;
